### PR TITLE
migrated null safety

### PR DESCRIPTION
**Pull request by AhmetMelihSerter**
Migrated null safety.

### CODE REVIEW

**Comment by Juniorlpes** [comment]
I'm using your package and I had this build error:

e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\git\gallery_saver-b828a940b31f011aa3755336408929abc4728881\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (20, 17): Redeclaration: FileUtils
e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\git\gallery_saver-b828a940b31f011aa3755336408929abc4728881\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (12, 12): Redeclaration: MediaType
e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\git\gallery_saver-b828a940b31f011aa3755336408929abc4728881\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (16, 7): Redeclaration: GallerySaver
e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\git\gallery_saver-b828a940b31f011aa3755336408929abc4728881\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaverPlugin.kt: (9, 7): Redeclaration: GallerySaverPlugin
e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (20, 17): Redeclaration: FileUtils
e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (12, 12): Redeclaration: MediaType
e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (16, 7): Redeclaration: GallerySaver
e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaverPlugin.kt: (9, 7): Redeclaration: GallerySaverPlugin
e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaverPlugin.kt: (19, 28): Cannot access '<init>': it is private in 'GallerySaverPlugin'

**Comment by AhmetMelihSerter** [comment]
> I'm using your package and I had this build error:
> 
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\git\gallery_saver-b828a940b31f011aa3755336408929abc4728881\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (20, 17): Redeclaration: FileUtils
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\git\gallery_saver-b828a940b31f011aa3755336408929abc4728881\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (12, 12): Redeclaration: MediaType
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\git\gallery_saver-b828a940b31f011aa3755336408929abc4728881\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (16, 7): Redeclaration: GallerySaver
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\git\gallery_saver-b828a940b31f011aa3755336408929abc4728881\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaverPlugin.kt: (9, 7): Redeclaration: GallerySaverPlugin
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\FileUtils.kt: (20, 17): Redeclaration: FileUtils
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (12, 12): Redeclaration: MediaType
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaver.kt: (16, 7): Redeclaration: GallerySaver
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaverPlugin.kt: (9, 7): Redeclaration: GallerySaverPlugin
> e: C:\Users\nilton.bento\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\gallery_saver-2.0.3\android\src\main\kotlin\carnegietechnologies\gallery_saver\GallerySaverPlugin.kt: (19, 28): Cannot access '': it is private in 'GallerySaverPlugin'

Please run the example in the package. It works smoothly for me.

**Comment by Steven-Chen87** [comment]
when will this fix publish?

**Comment by jayjun** [comment]
#100 is merged.

@AhmetMelihSerter Consider closing this if changes are the same.

**Comment by AhmetMelihSerter** [comment]
> #100 is merged.
> 
> @AhmetMelihSerter Consider closing this if changes are the same.

:+1:

**Pull request closed without merging**
