### PR TITLE
Add a workaround of the crash for Android

### PR DESCRIPTION
**Pull request by tattn**
My app was crashed on saving images (Pixel 3a).
So I added this workaround.

related issue: https://github.com/CarnegieTechnologies/gallery_saver/issues/58

### CODE REVIEW

**Comment by marcobraghim** [comment]
Please, I need this PR to be accepted, it fixes for me too.

**Comment by laeo** [comment]
Nice PR, it works for me! Please consider merge it!

**Comment by projexe** [comment]
Does this workaround still retain the library functionality (i.e. is the image still copied to the Gallery?) or is it just preventing an app from crashing on Android 11?

**Comment by ened** [comment]
@jelenalecic hi there, will you consider this PR?

**Pull request closed without merging**
