### PR TITLE
Compatibility with android 11 (scoped storage)

### LINKED ISSUE #98: Parameter albumName doesn't seem to be working
I'm trying to save photo into some "albumName":

        await GallerySaver.saveImage(f.absolute.path, albumName: "MyName");
        
But the file is just among other global photos, no folder or directory MyName is created. The file is plainly stored in "..../Pictures/filename.jpg".

Version 2.0.3, Google Pixel 2.

### LINKED ISSUE #116: Android 11 support and MANAGE_EXTERNAL_STORAGE permission
Google started sending the following message to developers, that means we won't be able to use requestLegacyExternalStorage flag soon and even the alternative permission MANAGE_EXTERNAL_STORAGE will require good reason to get approval. Is that absolutely necessary to request this permission for this plugin, or we can get rid of it?

**Message from Google:** We've detected that your app contains the requestLegacyExternalStorage flag in the manifest file of 1 or more of your app bundles or APKs.

Developers with apps on devices running Android 11+ must use Scoped Storage to give users better access control over their device storage. To release your app on Android 11 or newer after May 5th, you must either:

Update your app to use more privacy friendly best practices, such as the Storage Access Framework or Media Store API
Update your app to declare the All files access (MANAGE_EXTERNAL_STORAGE) permission in the manifest file, and complete the All files access permission declaration in Play Console from May 5th
Remove the All files access permission from your app entirely
For apps targeting Android 11, the requestLegacyExternalStorage flag will be ignored. You must use the All files access permission to retain broad access.

Apps requesting access to the All files access permission without a permitted use will be removed from Google Play, and you won't be able to publish updates.

### PR DESCRIPTION
**Pull request by bramdekker**
I made some changes so the package is compatible with Android 11 scoped storage.
Changes I made:
  - dont ask for permission to save if api >= 29
  - dont store image thumbnail if api >= 29
  - some changes to contentValues based on api version (added MediaStore.Images.Media.RELATIVE_PATH for albumName)

PS. In my application I only save images. So I only tested with images and all seem to work fine. I just copied the changes I made to contentValues to the insertVideo function, but didn't test it due to lack of time. I assumed it worked the same as the insertImage function regarding the contentValues. 

Fixes #116 
Fixes #98

### CODE REVIEW

**Comment by lecicdjuro** [comment]
Great, thx a lot. After testing, this will be merged and we will publish new version

**Comment by marcoberetta96** [comment]
Nice work! Waiting for merge :)

**Comment by miyura** [comment]
Appreciate if we can get this PR merged!

**Comment by armandojimenez** [comment]
Merge please!

**Review by lecicdjuro — APPROVED** [review]

**Pull request merged**
