### PR TITLE
Migrated to null safety

### PR DESCRIPTION
**Pull request by Saad29**
Updated plugins to null safety version and also used Dart migrate tool to migrate to null safety

### CODE REVIEW

**Review by Jartz — APPROVED** [review]

**Review by razvantmzz — APPROVED** [review]

**Comment by SirusCodes** [comment]
closes #99

**Comment by SirusCodes** [comment]
When this will be merged?

**Comment by Saad29** [comment]
When is the plugin goint to be updated to refelct this change?

**Comment by lecicdjuro** [comment]
Today i will publish new version

**Pull request merged**
